version: '3'

services:
  hcms_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'hcms_database'
      MYSQL_USER: 'hcms_website'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'website789'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - hcms_db
    environment:
      PMA_HOST: hcms_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80    

  hcms_migration:
    image: ttimot24/horizont-cms:latest
    depends_on: 
        - hcms_db
    command: sh -c 'php artisan migrate --no-interaction --force && php artisan db:seed --no-interaction --force && php artisan --version && php artisan hcms:user --create-admin --name=Administrator --email=admin@admin.com --username=admin --password=admin1'
    environment:
        DB_HOST: 'hcms_db'
        DB_CONNECTION: 'mysql'
        DB_USERNAME: 'hcms_website'
        DB_PASSWORD: 'website789'
        DB_DATABASE: 'hcms_database'
        DB_TABLE_PREFIX: 'hcms_'

  hcms_admin_user:
    image: ttimot24/horizont-cms:latest
    depends_on: 
        - hcms_migration
    command: sh -c 'php artisan hcms:user --create-admin --name=Administrator --email=admin@admin.com --username=admin --password=admin1'
    environment:
        INSTALLED: 'true'
        DB_HOST: 'hcms_db'
        DB_CONNECTION: 'mysql'
        DB_USERNAME: 'hcms_website'
        DB_PASSWORD: 'website789'
        DB_DATABASE: 'hcms_database'
        DB_TABLE_PREFIX: 'hcms_'

  hcms_web:
    image: ttimot24/horizont-cms:latest
    depends_on: 
        - hcms_migration
    environment:
        INSTALLED: 'true'
        DB_HOST: 'hcms_db'
        DB_CONNECTION: 'mysql'
        DB_USERNAME: 'hcms_website'
        DB_PASSWORD: 'website789'
        DB_DATABASE: 'hcms_database'
        DB_TABLE_PREFIX: 'hcms_'
    ports:
      - '8099:80'

volumes:
      - hcms-db:/var/lib/mysql

volumes:
  hcms-db:

networks:
    default:
        name: hcms-network
