name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: alpine-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite Unit
    
  docker_image:
    runs-on: alpine-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ttimot24/horizont-cms:latest
